name: helloworld  #name of the workflow
on: workflow_dispatch # on what condition it has to trigger    
jobs:            # name of the job
  hello:
  runs-on: ubuntu-latest      # it has to run on a VM
  steps:
    - name: hellostep
     run: echo print "helloworld"
  
